version: 3

tasks:
  clean:
    desc: Clean
    cmds:
      - rm -rf build dist

  install:
    desc: Install
    cmds:
      - pnpm install && pnpm prune

  build:
    desc: Build
    deps: [ install ]
    cmds:
      - pnpm run build

  run:
    desc: Run
    aliases: [ dev ]
    deps: [ install ]
    cmds:
      - pnpm run dev

  outdated:
    desc: Outdated
    aliases: [ dependencyUpdates ]
    deps: [ install ]
    cmds:
      - pnpm outdated
