version: 3

tasks:
  clean:
    desc: Clean
    cmds:
      - rm -rf build dist

  install:
    desc: Install
    cmds:
      - pnpm install && pnpm prune

  build:
    desc: Build
    deps: [ install ]
    cmds:
      - pnpm run build

  outdated:
    desc: Outdated
    aliases: [ dependencyUpdates ]
    deps: [ install ]
    cmds:
      - pnpm outdated

  site-clean:
    desc: Clean site
    cmds:
      - rm -rf build/gh-pages

  site-build:
    desc: Build site
    cmds:
      - task: site-clean
      - mkdir -p build/gh-pages
      - task: site-build-mdbook
      - task: site-build-typedoc
      - task: site-build-example-vanilla
      - task: site-build-example-svelte

  site-deploy:
    desc: Deploy site
    deps: [ site-build ]
    cmds:
      - pnpm run site:deploy

  site-build-mdbook:
    desc: Generate mdbook
    cmds:
      - mdbook build --dest-dir $(pwd)/build/gh-pages docs/mdbook

  site-build-typedoc:
    desc: Generate typedoc
    cmds:
      - pnpm run typedoc

  site-build-example-vanilla:
    cmds:
      - cd examples/vanilla && mise exec -- task build
      - mkdir -p build/gh-pages/projects/vanilla
      - cp -r examples/vanilla/dist/* build/gh-pages/projects/vanilla

  site-build-example-svelte:
    cmds:
      - cd examples/svelte && mise exec -- task build
      - mkdir -p build/gh-pages/projects/svelte
      - cp -r examples/svelte/dist/* build/gh-pages/projects/svelte

  site-serve:
    desc: Site - Serve
    deps: [ site-build ]
    cmds:
      - caddy file-server --root build/gh-pages --listen 127.0.0.1:8080
